# Generated by Django 5.2.6 on 2026-04-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_display', models.CharField(blank=True, help_text='e.g. Full Tuition + Living Expenses', max_length=150, null=True)),
                ('funding_type', models.CharField(choices=[('full', 'Full Funding'), ('partial', 'Partial Funding')], default='full', max_length=10)),
                ('category', models.CharField(choices=[('merit', 'Merit-Based'), ('need', 'Need-Based'), ('sports', 'Sports'), ('research', 'Research')], default='merit', max_length=50)),
                ('deadline', models.DateField()),
                ('target_group', models.CharField(blank=True, help_text='e.g. Graduate Students', max_length=150, null=True)),
                ('recipients_per_year', models.CharField(blank=True, help_text='e.g. 4,000', max_length=50, null=True)),
                ('min_gpa_required', models.FloatField(blank=True, null=True)),
                ('min_ielts_required', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='universities.university')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
