# Generated by Django 6.0.4 on 2026-04-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={},
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='eligibility',
        ),
    ]
