# Generated by Django 6.0.4 on 2026-05-07 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_consultant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'consultant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
