# Generated by Django 6.0.4 on 2026-04-23 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0002_alter_program_id_alter_university_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='incomplete', max_length=20)),
                ('personal_statement', models.BooleanField(default=False)),
                ('transcripts', models.BooleanField(default=False)),
                ('recommendations', models.BooleanField(default=False)),
                ('english_test', models.BooleanField(default=False)),
                ('financial_docs', models.BooleanField(default=False)),
                ('cv_resume', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='universities.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('user', 'university', 'program')},
            },
        ),
    ]
