# Generated by Django 6.0.4 on 2026-04-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv_resume',
            field=models.FileField(blank=True, null=True, upload_to='applications/cv_resumes/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='english_test',
            field=models.FileField(blank=True, null=True, upload_to='applications/english_tests/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='financial_docs',
            field=models.FileField(blank=True, null=True, upload_to='applications/financial_docs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='personal_statement',
            field=models.FileField(blank=True, null=True, upload_to='applications/personal_statements/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='recommendations',
            field=models.FileField(blank=True, null=True, upload_to='applications/recommendations/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transcripts',
            field=models.FileField(blank=True, null=True, upload_to='applications/transcripts/'),
        ),
    ]
