# Generated by Django 6.0.4 on 2026-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_cv_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='intake_season',
            field=models.CharField(blank=True, choices=[('fall_2025', 'Fall 2025'), ('spring_2026', 'Spring 2026'), ('fall_2026', 'Fall 2026'), ('spring_2027', 'Spring 2027'), ('rolling', 'Rolling / Anytime')], max_length=20, null=True),
        ),
    ]
