# Generated by Django 6.0.4 on 2026-05-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_intake_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='shared_with_consultant',
            field=models.BooleanField(default=False),
        ),
    ]
