# Generated by Django 6.0.4 on 2026-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('tuition_range', models.CharField(max_length=100)),
                ('intake', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
