# Generated by Django 5.2.6 on 2026-04-22 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('tuition_display', models.CharField(blank=True, help_text='e.g. $54,000/yr', max_length=100, null=True)),
                ('acceptance_rate', models.FloatField(blank=True, help_text='e.g. 4.5 for 4.5%', null=True)),
                ('rating', models.FloatField(blank=True, help_text='e.g. 4.9', null=True)),
                ('total_students', models.CharField(blank=True, max_length=50, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('min_gpa', models.FloatField(blank=True, help_text='Minimum GPA required', null=True)),
                ('min_ielts', models.FloatField(blank=True, help_text='Minimum IELTS score', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD'), ('mba', 'MBA')], default='master', max_length=20)),
                ('duration', models.CharField(blank=True, help_text='e.g. 2 years', max_length=50, null=True)),
                ('tuition_per_year', models.CharField(blank=True, max_length=100, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
